In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [36]:
import pandas as pd
csv_file_path = '/content/drive/MyDrive/Database for DA project/Tima_CRM - Sheet1.csv'
df = pd.read_csv(csv_file_path)
# Display the first 5 rows of the DataFrame
display(df.head())

,STT,SoTienDKVayBanDau,TienGiaiNgan,SoTienConLai,application_date,TS_CREDIT_SCORE_V2,Số điện thoại khách hàng,FromDate,ID,LoanID,...,InterestPaymentType,LongestOverdue,CreditInfo,Name,Address,CheckTime,Brieft,NumberOfLoans,HasBadDebt,HasLatePayment
0,2,10000000.0,NaN,0,2023-02-30,403,977966899,2016-06-24 00:00:00,40,16104,...,Lãi ngày,4,NaN,NaN,NaN,2019-03-17 11:22:15,notfound,-1,0,0
1,3,NaN,250000.0,0,2016-07-28,403,977966899,2016-07-28 00:00:00,226,20871,...,Lãi ngày,147,NaN,NaN,NaN,2019-03-17 11:22:15,notfound,-1,0,0
2,4,5000000.0,5000000.0,-50000,2016-06-29,531,397511119,2016-06-29 00:00:00,45,17049,...,Lãi ngày,3,"Khách hàng hiện không có quan hệ tại TCTD, khô...",DAO CONG QUYET,"P203-E9 PHUONG MAI,DONG DA,HA NOI",2019-03-17 08:29:24,0,0,0,0
3,5,10000000.0,10000000.0,0,2016-06-29,588,abc1234567,2016-06-29 00:00:00,48,17067,...,Lãi ngày,16,"Khách hàng hiện không có quan hệ tại TCTD, khô...",NGUYEN ANH VU,SO 21 NGACH 77/4 LE HONG PHONG-DIEN BIEN-BA DI...,2019-03-17 08:28:09,0,0,0,0
4,6,10000000.0,10000000.0,0,2016-08-05,675,966710180,2016-08-05 00:00:00,293,22390,...,Lãi ngày,8,"Khách hàng hiện không có quan hệ tại TCTD, khô...",ĐÀO NGỌC LINH,"-, TT CỤC KHÍ TƯỢNG THỦY VĂN, TRUNG LIỆT, Q.ĐỐ...",2019-03-17 14:14:22,0,0,0,0

In [42]:
# Check the number of missing values in each column
print("Number of missing values by column:")
print(df.isnull().sum())

Number of missing values by column:
application_date                  0
TS_CREDIT_SCORE_V2                0
Số điện thoại khách hàng          0
FromDate                          0
ID                                0
LoanID                            0
Số tiền đăng ký vay ban đầu       0
Tiền giải ngân                    0
Tiền gốc còn lại                  0
ToDate                            0
Trạng thái                        0
FullName                          0
CardNumber                        0
Gender                            4
Birthday                          4
CityName                          0
DistrictName                      0
WardName                       1716
Hình thức cư trú                142
Thời gian đã sống               164
Street                            0
CityNameHouseHold                36
DistrictNameHouseHold            40
WardNameHouseHold                29
JobName                           0
NameCompany                       0
AddressCompany                    0
CityCompany                     610
DistrictNameCompany              40
Salary                            5
ReceiveYourIncomeSalary        1943
DescriptionPositionJob            0
RelativeFamilyName                0
FullNameFamily                    0
ProductCreditName                 1
InterestPaymentType               0
LongestOverdue                    0
CreditInfo                      217
Name                              0
Address                           0
CheckTime                         5
Brieft                            0
NumberOfLoans                     0
HasBadDebt                        0
HasLatePayment                    0
dtype: int64

#Remove Duplicate Rows

In [19]:
print(f"DataFrame shape before dropping duplicates: {df.shape}")

df = df.drop_duplicates()

print(f"DataFrame shape after dropping duplicates: {df.shape}")
display(df.head())

DataFrame shape before dropping duplicates: (2383, 49)
DataFrame shape after dropping duplicates: (2383, 49)

,STT,SoTienDKVayBanDau,TienGiaiNgan,SoTienConLai,application_date,TS_CREDIT_SCORE_V2,Số điện thoại khách hàng,FromDate,ID,LoanID,...,InterestPaymentType,LongestOverdue,CreditInfo,Name,Address,CheckTime,Brieft,NumberOfLoans,HasBadDebt,HasLatePayment
0,2,10000000.0,NaN,0,2023-02-30,403,977966899,2016-06-24 00:00:00,40,16104,...,Lãi ngày,4,NaN,NaN,NaN,2019-03-17 11:22:15,notfound,-1,0,0
1,3,NaN,250000.0,0,2016-07-28,403,977966899,2016-07-28 00:00:00,226,20871,...,Lãi ngày,147,NaN,NaN,NaN,2019-03-17 11:22:15,notfound,-1,0,0
2,4,5000000.0,5000000.0,-50000,2016-06-29,531,397511119,2016-06-29 00:00:00,45,17049,...,Lãi ngày,3,"Khách hàng hiện không có quan hệ tại TCTD, khô...",DAO CONG QUYET,"P203-E9 PHUONG MAI,DONG DA,HA NOI",2019-03-17 08:29:24,0,0,0,0
3,5,10000000.0,10000000.0,0,2016-06-29,588,abc1234567,2016-06-29 00:00:00,48,17067,...,Lãi ngày,16,"Khách hàng hiện không có quan hệ tại TCTD, khô...",NGUYEN ANH VU,SO 21 NGACH 77/4 LE HONG PHONG-DIEN BIEN-BA DI...,2019-03-17 08:28:09,0,0,0,0
4,6,10000000.0,10000000.0,0,2016-08-05,675,966710180,2016-08-05 00:00:00,293,22390,...,Lãi ngày,8,"Khách hàng hiện không có quan hệ tại TCTD, khô...",ĐÀO NGỌC LINH,"-, TT CỤC KHÍ TƯỢNG THỦY VĂN, TRUNG LIỆT, Q.ĐỐ...",2019-03-17 14:14:22,0,0,0,0

#Delete 4 first columns which are not neccessary and duplicated

In [54]:
# Drop 4 unnecessary columns
df = df.drop(columns=['STT', 'SoTienDKVayBanDau', 'TienGiaiNgan', 'SoTienConLai'])

print("✅ 4 columns have been removed.")
print("New shape:", df.shape)

KeyError: "['STT', 'SoTienDKVayBanDau', 'TienGiaiNgan', 'SoTienConLai'] not found in axis"

#Current Data Types of Columns

In [55]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 45 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   application_date             2383 non-null   object
 1   TS_CREDIT_SCORE_V2           2383 non-null   int64
 2   Số điện thoại khách hàng     2383 non-null   object
 3   FromDate                     2383 non-null   object
 4   ID                           2383 non-null   int64
 5   LoanID                       2383 non-null   int64
 6   Số tiền đăng ký vay ban đầu  2383 non-null   int64
 7   Tiền giải ngân               2383 non-null   int64
 8   Tiền gốc còn lại             2383 non-null   int64
 9   ToDate                       2383 non-null   object
 10  Trạng thái                   2383 non-null   object
 11  FullName                     2383 non-null   object
 12  CardNumber                   2383 non-null   int64
 13  Gender                       2379 non-null   object
 14  Birthday                     2379 non-null   object
 15  CityName                     2383 non-null   object
 16  DistrictName                 2383 non-null   object
 17  WardName                     2383 non-null   object
 18  Hình thức cư trú             2383 non-null   object
 19  Thời gian đã sống            2383 non-null   object
 20  Street                       2383 non-null   object
 21  CityNameHouseHold            2347 non-null   object
 22  DistrictNameHouseHold        2343 non-null   object
 23  WardNameHouseHold            2354 non-null   object
 24  JobName                      2383 non-null   object
 25  NameCompany                  2383 non-null   object
 26  AddressCompany               2383 non-null   object
 27  CityCompany                  2383 non-null   object
 28  DistrictNameCompany          2383 non-null   object
 29  Salary                       2383 non-null   float64
 30  ReceiveYourIncomeSalary      2383 non-null   object
 31  DescriptionPositionJob       2383 non-null   object
 32  RelativeFamilyName           2383 non-null   object
 33  FullNameFamily               2383 non-null   object
 34  ProductCreditName            2382 non-null   object
 35  InterestPaymentType          2383 non-null   object
 36  LongestOverdue               2383 non-null   int64
 37  CreditInfo                   2383 non-null   object
 38  Name                         2383 non-null   object
 39  Address                      2383 non-null   object
 40  CheckTime                    2383 non-null   object
 41  Brieft                       2383 non-null   object
 42  NumberOfLoans                2383 non-null   int64
 43  HasBadDebt                   2383 non-null   int64
 44  HasLatePayment               2383 non-null   int64
dtypes: float64(1), int64(11), object(33)
memory usage: 837.9+ KB

#Converting Date Columns to Datetime Type

In [56]:
date_columns = ['application_date', 'FromDate', 'ToDate', 'Birthday', 'CheckTime']

for col in date_columns:
    df[col] = pd.to_datetime(df[col], errors='coerce')

print("Data types after conversion:")
df.info()

Data types after conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 45 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   application_date             2382 non-null   datetime64[ns]
 1   TS_CREDIT_SCORE_V2           2383 non-null   int64
 2   Số điện thoại khách hàng     2383 non-null   object
 3   FromDate                     2383 non-null   datetime64[ns]
 4   ID                           2383 non-null   int64
 5   LoanID                       2383 non-null   int64
 6   Số tiền đăng ký vay ban đầu  2383 non-null   int64
 7   Tiền giải ngân               2383 non-null   int64
 8   Tiền gốc còn lại             2383 non-null   int64
 9   ToDate                       2383 non-null   datetime64[ns]
 10  Trạng thái                   2383 non-null   object
 11  FullName                     2383 non-null   object
 12  CardNumber                   2383 non-null   int64
 13  Gender                       2379 non-null   object
 14  Birthday                     2378 non-null   datetime64[ns]
 15  CityName                     2383 non-null   object
 16  DistrictName                 2383 non-null   object
 17  WardName                     2383 non-null   object
 18  Hình thức cư trú             2383 non-null   object
 19  Thời gian đã sống            2383 non-null   object
 20  Street                       2383 non-null   object
 21  CityNameHouseHold            2347 non-null   object
 22  DistrictNameHouseHold        2343 non-null   object
 23  WardNameHouseHold            2354 non-null   object
 24  JobName                      2383 non-null   object
 25  NameCompany                  2383 non-null   object
 26  AddressCompany               2383 non-null   object
 27  CityCompany                  2383 non-null   object
 28  DistrictNameCompany          2383 non-null   object
 29  Salary                       2383 non-null   float64
 30  ReceiveYourIncomeSalary      2383 non-null   object
 31  DescriptionPositionJob       2383 non-null   object
 32  RelativeFamilyName           2383 non-null   object
 33  FullNameFamily               2383 non-null   object
 34  ProductCreditName            2382 non-null   object
 35  InterestPaymentType          2383 non-null   object
 36  LongestOverdue               2383 non-null   int64
 37  CreditInfo                   2383 non-null   object
 38  Name                         2383 non-null   object
 39  Address                      2383 non-null   object
 40  CheckTime                    2236 non-null   datetime64[ns]
 41  Brieft                       2383 non-null   object
 42  NumberOfLoans                2383 non-null   int64
 43  HasBadDebt                   2383 non-null   int64
 44  HasLatePayment               2383 non-null   int64
dtypes: datetime64[ns](5), float64(1), int64(11), object(28)
memory usage: 837.9+ KB

/tmp/ipykernel_527/3110979693.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors='coerce')

#Converting Numerical Columns to Appropriate Types

In [57]:
float_cols = ['Số tiền đăng ký vay ban đầu', 'Tiền giải ngân', 'Tiền gốc còn lại']
for col in float_cols:
    df[col] = df[col].astype('float64')

# Convert 'Salary' to float64, coercing errors to NaN
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

print("Data types after numerical conversion:")
df.info()

Data types after numerical conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 45 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   application_date             2382 non-null   datetime64[ns]
 1   TS_CREDIT_SCORE_V2           2383 non-null   int64
 2   Số điện thoại khách hàng     2383 non-null   object
 3   FromDate                     2383 non-null   datetime64[ns]
 4   ID                           2383 non-null   int64
 5   LoanID                       2383 non-null   int64
 6   Số tiền đăng ký vay ban đầu  2383 non-null   float64
 7   Tiền giải ngân               2383 non-null   float64
 8   Tiền gốc còn lại             2383 non-null   float64
 9   ToDate                       2383 non-null   datetime64[ns]
 10  Trạng thái                   2383 non-null   object
 11  FullName                     2383 non-null   object
 12  CardNumber                   2383 non-null   int64
 13  Gender                       2379 non-null   object
 14  Birthday                     2378 non-null   datetime64[ns]
 15  CityName                     2383 non-null   object
 16  DistrictName                 2383 non-null   object
 17  WardName                     2383 non-null   object
 18  Hình thức cư trú             2383 non-null   object
 19  Thời gian đã sống            2383 non-null   object
 20  Street                       2383 non-null   object
 21  CityNameHouseHold            2347 non-null   object
 22  DistrictNameHouseHold        2343 non-null   object
 23  WardNameHouseHold            2354 non-null   object
 24  JobName                      2383 non-null   object
 25  NameCompany                  2383 non-null   object
 26  AddressCompany               2383 non-null   object
 27  CityCompany                  2383 non-null   object
 28  DistrictNameCompany          2383 non-null   object
 29  Salary                       2383 non-null   float64
 30  ReceiveYourIncomeSalary      2383 non-null   object
 31  DescriptionPositionJob       2383 non-null   object
 32  RelativeFamilyName           2383 non-null   object
 33  FullNameFamily               2383 non-null   object
 34  ProductCreditName            2382 non-null   object
 35  InterestPaymentType          2383 non-null   object
 36  LongestOverdue               2383 non-null   int64
 37  CreditInfo                   2383 non-null   object
 38  Name                         2383 non-null   object
 39  Address                      2383 non-null   object
 40  CheckTime                    2236 non-null   datetime64[ns]
 41  Brieft                       2383 non-null   object
 42  NumberOfLoans                2383 non-null   int64
 43  HasBadDebt                   2383 non-null   int64
 44  HasLatePayment               2383 non-null   int64
dtypes: datetime64[ns](5), float64(4), int64(8), object(28)
memory usage: 837.9+ KB

#Converting Object Columns to Category Type

In [58]:
category_cols = ['Thời gian đã sống', 'Gender', 'Trạng thái', 'ProductCreditName', 'InterestPaymentType', 'Hình thức cư trú', 'ReceiveYourIncomeSalary', 'HasBadDebt', 'HasLatePayment']

for col in category_cols:
    df[col] = df[col].astype('category')

print("Data types after category conversion:")
df.info()

Data types after category conversion:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2383 entries, 0 to 2382
Data columns (total 45 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   application_date             2382 non-null   datetime64[ns]
 1   TS_CREDIT_SCORE_V2           2383 non-null   int64
 2   Số điện thoại khách hàng     2383 non-null   object
 3   FromDate                     2383 non-null   datetime64[ns]
 4   ID                           2383 non-null   int64
 5   LoanID                       2383 non-null   int64
 6   Số tiền đăng ký vay ban đầu  2383 non-null   float64
 7   Tiền giải ngân               2383 non-null   float64
 8   Tiền gốc còn lại             2383 non-null   float64
 9   ToDate                       2383 non-null   datetime64[ns]
 10  Trạng thái                   2383 non-null   category
 11  FullName                     2383 non-null   object
 12  CardNumber                   2383 non-null   int64
 13  Gender                       2379 non-null   category
 14  Birthday                     2378 non-null   datetime64[ns]
 15  CityName                     2383 non-null   object
 16  DistrictName                 2383 non-null   object
 17  WardName                     2383 non-null   object
 18  Hình thức cư trú             2383 non-null   category
 19  Thời gian đã sống            2383 non-null   category
 20  Street                       2383 non-null   object
 21  CityNameHouseHold            2347 non-null   object
 22  DistrictNameHouseHold        2343 non-null   object
 23  WardNameHouseHold            2354 non-null   object
 24  JobName                      2383 non-null   object
 25  NameCompany                  2383 non-null   object
 26  AddressCompany               2383 non-null   object
 27  CityCompany                  2383 non-null   object
 28  DistrictNameCompany          2383 non-null   object
 29  Salary                       2383 non-null   float64
 30  ReceiveYourIncomeSalary      2383 non-null   category
 31  DescriptionPositionJob       2383 non-null   object
 32  RelativeFamilyName           2383 non-null   object
 33  FullNameFamily               2383 non-null   object
 34  ProductCreditName            2382 non-null   category
 35  InterestPaymentType          2383 non-null   category
 36  LongestOverdue               2383 non-null   int64
 37  CreditInfo                   2383 non-null   object
 38  Name                         2383 non-null   object
 39  Address                      2383 non-null   object
 40  CheckTime                    2236 non-null   datetime64[ns]
 41  Brieft                       2383 non-null   object
 42  NumberOfLoans                2383 non-null   int64
 43  HasBadDebt                   2383 non-null   category
 44  HasLatePayment               2383 non-null   category
dtypes: category(9), datetime64[ns](5), float64(4), int64(6), object(21)
memory usage: 693.4+ KB

#Converting Remaining Object Columns to String Type

In [59]:
string_cols = ['ID', 'LoanID', 'Số điện thoại khách hàng', 'FullName', 'CityName', 'DistrictName', 'WardName', 'Street', 'CityNameHouseHold', 'DistrictNameHouseHold', 'WardNameHouseHold', 'JobName', 'NameCompany', 'AddressCompany', 'CityCompany', 'DistrictNameCompany', 'DescriptionPositionJob', 'RelativeFamilyName', 'FullNameFamily', 'CreditInfo', 'Name', 'Address', 'Brieft']

df[string_cols] = df[string_cols].astype('string')

print("Covert to string dtype")

print(df[string_cols].dtypes)

Covert to string dtype
ID                          string[python]
LoanID                      string[python]
Số điện thoại khách hàng    string[python]
FullName                    string[python]
CityName                    string[python]
DistrictName                string[python]
WardName                    string[python]
Street                      string[python]
CityNameHouseHold           string[python]
DistrictNameHouseHold       string[python]
WardNameHouseHold           string[python]
JobName                     string[python]
NameCompany                 string[python]
AddressCompany              string[python]
CityCompany                 string[python]
DistrictNameCompany         string[python]
DescriptionPositionJob      string[python]
RelativeFamilyName          string[python]
FullNameFamily              string[python]
CreditInfo                  string[python]
Name                        string[python]
Address                     string[python]
Brieft                      string[python]
dtype: object

#Processing GENDER, HASBADDEBT, HASLATEPAYMENT column

In [60]:
# ====================== PROCESSING GENDER COLUMN ======================

# Step 1: Convert to string and remove extra spaces
df['Gender'] = df['Gender'].astype(str).str.strip()

# Step 2: Replace values and handle NaN
df['Gender'] = df['Gender'].replace({
    '0': 'Male',
    '1': 'Female',
    'nan': 'Unknown',
    'NaN': 'Unknown',
    'None': 'Unknown'
})

# Step 3: Fill any remaining NaN values
df['Gender'] = df['Gender'].fillna('Unknown')

# Step 4: Convert to category type (best practice for categorical data)
df['Gender'] = df['Gender'].astype('category')

# ====================== CHECK RESULT ======================
print("✅ Gender column after processing:")
print(df['Gender'].value_counts(dropna=False))
print("\nData type:", df['Gender'].dtype)

✅ Gender column after processing:
Gender
Male       1520
Female      859
Unknown       4
Name: count, dtype: int64

Data type: category

In [61]:
# ====================== PROCESSING HasBadDebt & HasLatePayment ======================

# Processing HasBadDebt
df['HasBadDebt'] = df['HasBadDebt'].astype(str).str.strip().replace({
    '0': 'No',
    '1': 'Yes'
}).astype('category')

# Processing HasLatePayment
df['HasLatePayment'] = df['HasLatePayment'].astype(str).str.strip().replace({
    '0': 'No',
    '1': 'Yes'
}).astype('category')

# ====================== Check result ======================
print("✅ Kết quả sau khi xử lý 2 cột:\n")

print("HasBadDebt value counts:")
print(df['HasBadDebt'].value_counts(dropna=False))

print("\nHasLatePayment value counts:")
print(df['HasLatePayment'].value_counts(dropna=False))

print("\nData types:")
print(df[['HasBadDebt', 'HasLatePayment']].dtypes)

✅ Kết quả sau khi xử lý 2 cột:

HasBadDebt value counts:
HasBadDebt
No     2121
Yes     262
Name: count, dtype: int64

HasLatePayment value counts:
HasLatePayment
No     2047
Yes     336
Name: count, dtype: int64

Data types:
HasBadDebt        category
HasLatePayment    category
dtype: object

#Standardize Text Columns

In [62]:
# List of columns to standardize
text_cols = ['FullName', 'Name', 'RelativeFamilyName', 'FullNameFamily',
             'NameCompany', 'Street', 'Address', 'AddressCompany',
             'DescriptionPositionJob', 'JobName', 'Brief']

# Apply standardization
for col in text_cols:
    if col in df.columns:
        # Convert to string and remove extra spaces
        df[col] = df[col].astype(str).str.strip()

        # Replace real NaN values with 'Unknown'
        df[col] = df[col].replace(['nan', 'NaN', 'None', 'NAN'], 'Unknown')

        # Fill any remaining NaN
        df[col] = df[col].fillna('Unknown')

        # Convert to Title Case
        df[col] = df[col].str.title()
        print(f"✓ Đã chuẩn hóa cột: {col}")
    else:
        print(f"⚠ Cột {col} không tồn tại")

# Check result
print("\n===SAMPLE RESULTS AFTER PROCESSING===")
for col in ['FullName', 'NameCompany', 'Street']:
    if col in df.columns:
        print(f"\n{col}:")
        print(df[col].head(10))

✓ Đã chuẩn hóa cột: FullName
✓ Đã chuẩn hóa cột: Name
✓ Đã chuẩn hóa cột: RelativeFamilyName
✓ Đã chuẩn hóa cột: FullNameFamily
✓ Đã chuẩn hóa cột: NameCompany
✓ Đã chuẩn hóa cột: Street
✓ Đã chuẩn hóa cột: Address
✓ Đã chuẩn hóa cột: AddressCompany
✓ Đã chuẩn hóa cột: DescriptionPositionJob
✓ Đã chuẩn hóa cột: JobName
⚠ Cột Brief không tồn tại

===SAMPLE RESULTS AFTER PROCESSING===

FullName:
0     Phạm Sơn Tùng
1     Phạm Sơn Tùng
2    Đào Công Quyết
3             12345
4     Đào Ngọc Linh
5     Đào Ngọc Linh
6     Đỗ Minh Trang
7     Dương Minh Hà
8     Dương Minh Hà
9    Trần Minh Tuấn
Name: FullName, dtype: object

NameCompany:
0                               Công An Quận Hoàng Mai
1                               Công An Quận Hoàng Mai
2                                   Dai Su Quan Kuwait
3     Công Ty Tnhh Thương Mại Vận Tải Du Lịch Mai Long
4    Trung Tâm Tư Vấn Và Dịch Vụ Tài Nguyên Môi Trường
5    Trung Tâm Tư Vấn Và Dịch Vụ Tài Nguyên Môi Trường
6     Công Ty Cổ Phần Phát Triển Thương Hiệu Hoàng Gia
7                           Công Ty Cổ Phần Pin Hà Nội
8                           Công Ty Cổ Phần Pin Hà Nội
9                                              Tại Gia
Name: NameCompany, dtype: object

Street:
0                                           Giải Phóng
1                                           Giải Phóng
2                                           Phuong Mai
3                                        Lê Hồng Phong
4      Ngõ 95 Chùa Bộc, Tập Thể Cục Khí Tượng Thủy Văn
5      Ngõ 95 Chùa Bộc, Tập Thể Cục Khí Tượng Thủy Văn
6                                   Ngõ Chợ Khâm Thiên
7    Tòa Ct1 - Tầng 21 Căn Hộ 21K1 Chung Cư Viện Bỏ...
8    Tòa Ct1 - Tầng 21 Căn Hộ 21K1 Chung Cư Viện Bỏ...
9                                            Định Công
Name: Street, dtype: object

#Fill missing values and handle data

In [68]:
# List of columns to fill NaN with 'Unknown'
fill_unknown_cols = [
    'WardName',
    'Hình thức cư trú',
    'Thời gian đã sống',
    'CityCompany',
    'DistrictNameCompany',
    'ReceiveYourIncomeSalary',
    'CreditInfo',
    'CheckTime'
]

# Fill missing values
for col in fill_unknown_cols:
    if col in df.columns:
        missing_count = df[col].isnull().sum()

        df[col] = df[col].fillna('Unknown')

        print(f"✓ Filled {missing_count} missing values in '{col}' with 'Unknown'")
    else:
        print(f"⚠ Column '{col}' not found in DataFrame")

# ====================== CHECK RESULT ======================
print("\nCompleted filling missing values with 'Unknown'")

# Summary of remaining missing values
print("\nRemaining missing values in selected columns:")
print(df[fill_unknown_cols].isnull().sum())

✓ Filled 0 missing values in 'WardName' with 'Unknown'
⚠ Column 'Hình thức cư trú' not found in DataFrame
⚠ Column 'Thời gian đã sống' not found in DataFrame
⚠ Column 'CityCompany' not found in DataFrame
⚠ Column 'DistrictNameCompany' not found in DataFrame
✓ Filled 0 missing values in 'ReceiveYourIncomeSalary' with 'Unknown'
✓ Filled 0 missing values in 'CreditInfo' with 'Unknown'
✓ Filled 147 missing values in 'CheckTime' with 'Unknown'

✅ Completed filling missing values with 'Unknown'

Remaining missing values in selected columns:

KeyError: "['Hình thức cư trú', 'Thời gian đã sống', 'CityCompany', 'DistrictNameCompany'] not in index"

In [82]:
# ====================== FILL MISSING VALUES ======================

# List of columns to fill with 'Unknown'
fill_unknown_cols = [
    'HouseholdDistrict',
    'HouseholdCity',
    'HouseholdWard',
    'Birthday',
    'application_date',
    'CheckTime'
]

# Fill 'Unknown' for selected columns
for col in fill_unknown_cols:
    if col in df.columns:
        missing_count = df[col].isnull().sum()
        df[col] = df[col].fillna('Unknown')
        print(f"✓ Filled {missing_count} missing values in '{col}' with 'Unknown'")

# Special handling for ProductCreditName - Fill with mode (most frequent value)
if 'ProductCreditName' in df.columns:
    mode_value = df['ProductCreditName'].mode()[0]  # Get the most common value
    missing_count = df['ProductCreditName'].isnull().sum()

    df['ProductCreditName'] = df['ProductCreditName'].fillna(mode_value)
    print(f"✓ Filled {missing_count} missing values in 'ProductCreditName' with mode: '{mode_value}'")

# ====================== FINAL CHECK ======================
print("\n" + "="*70)
print("MISSING VALUES FILLING COMPLETED!")

print("\nRemaining missing values:")
print(df[['HouseholdDistrict', 'HouseholdCity', 'HouseholdWard',
          'Birthday', 'application_date', 'ProductCreditName']].isnull().sum())

✓ Filled 0 missing values in 'HouseholdDistrict' with 'Unknown'
✓ Filled 0 missing values in 'HouseholdCity' with 'Unknown'
✓ Filled 0 missing values in 'HouseholdWard' with 'Unknown'
✓ Filled 0 missing values in 'Birthday' with 'Unknown'
✓ Filled 0 missing values in 'application_date' with 'Unknown'
✓ Filled 147 missing values in 'CheckTime' with 'Unknown'
✓ Filled 0 missing values in 'ProductCreditName' with mode: 'Cầm cố Điện thoại'

======================================================================
MISSING VALUES FILLING COMPLETED!

Remaining missing values:
HouseholdDistrict    0
HouseholdCity        0
HouseholdWard        0
Birthday             0
application_date     0
ProductCreditName    0
dtype: int64

In [51]:
#CLEAN & FILL SALARY COLUMN

# Step 1: Convert Salary to string first
df['Salary'] = df['Salary'].astype(str).str.strip()

# Step 2: Clean the column (remove special characters, $ , commas, etc.)
df['Salary'] = df['Salary'].replace({
    r'[$,]': '',           # Remove $ and comma
    r'Ten thousand': '10000',
    r'thousand': '000',
    r'[a-zA-Z]': '',       # Remove all letters
}, regex=True)

# Step 3: Convert to numeric
df['Salary'] = pd.to_numeric(df['Salary'], errors='coerce')

# Step 4: Fill missing values with median
median_salary = df['Salary'].median()
df['Salary'] = df['Salary'].fillna(median_salary)

print("Đã làm sạch và điền Salary thành công!")
print("Median Salary:", median_salary)
print("Remaining missing values:", df['Salary'].isnull().sum())
print("\nSummary:")
print(df['Salary'].describe().round(2))

Đã làm sạch và điền Salary thành công!
Median Salary: 9000000.0
Remaining missing values: 0

Summary:
count    2.383000e+03
mean     1.006103e+07
std      5.883427e+06
min      1.000000e+03
25%      7.000000e+06
50%      9.000000e+06
75%      1.100000e+07
max      1.000000e+08
Name: Salary, dtype: float64

In [73]:
#HANDLE SALARY = 0

print("Số lượng Salary = 0 trước khi xử lý:", (df['Salary'] == 0).sum())

# Tính median của những người có lương > 0
median_salary = df[df['Salary'] > 0]['Salary'].median()

# Thay Salary = 0 bằng median
df['Salary'] = df['Salary'].replace(0, median_salary)

print(f"Đã thay { (df['Salary'] == 0).sum() } giá trị Salary = 0 bằng median: {median_salary:,.0f}")

Số lượng Salary = 0 trước khi xử lý: 0
Đã thay 0 giá trị Salary = 0 bằng median: 9,000,000

In [63]:
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

for col in numeric_cols:
    unique_vals = sorted(df[col].dropna().unique())
    unique_count = len(unique_vals)

    print(f"🔹 Cột: {col}  |  Unique: {unique_count}")
    print(f"   Min: {df[col].min():,.2f}  |  Max: {df[col].max():,.2f}")

    if unique_count <= 50:
        print("   All unique values:", unique_vals)
    else:
        print("   First 15 values :", unique_vals[:15])
        print("   Last 15 values  :", unique_vals[-15:])

    print("-" * 80)

🔹 Cột: TS_CREDIT_SCORE_V2  |  Unique: 432
   Min: 300.00  |  Max: 826.00
   First 15 values : [np.int64(300), np.int64(301), np.int64(303), np.int64(307), np.int64(308), np.int64(310), np.int64(312), np.int64(314), np.int64(319), np.int64(320), np.int64(321), np.int64(322), np.int64(323), np.int64(324), np.int64(327)]
   Last 15 values  : [np.int64(775), np.int64(777), np.int64(778), np.int64(781), np.int64(786), np.int64(789), np.int64(790), np.int64(797), np.int64(805), np.int64(810), np.int64(811), np.int64(812), np.int64(815), np.int64(823), np.int64(826)]
--------------------------------------------------------------------------------
🔹 Cột: Số tiền đăng ký vay ban đầu  |  Unique: 55
   Min: 100,000.00  |  Max: 1,553,290,000.00
   First 15 values : [np.float64(100000.0), np.float64(1000000.0), np.float64(2000000.0), np.float64(2500000.0), np.float64(3000000.0), np.float64(4000000.0), np.float64(4120000.0), np.float64(5000000.0), np.float64(6000000.0), np.float64(6922000.0), np.float64(7000000.0), np.float64(8000000.0), np.float64(8500000.0), np.float64(9000000.0), np.float64(10000000.0)]
   Last 15 values  : [np.float64(100000000.0), np.float64(115000000.0), np.float64(120000000.0), np.float64(150000000.0), np.float64(160000000.0), np.float64(200000000.0), np.float64(240000000.0), np.float64(250000000.0), np.float64(300000000.0), np.float64(400000000.0), np.float64(500000000.0), np.float64(550000000.0), np.float64(600000000.0), np.float64(1023000000.0), np.float64(1553290000.0)]
--------------------------------------------------------------------------------
🔹 Cột: Tiền giải ngân  |  Unique: 57
   Min: 1,000,000.00  |  Max: 1,599,735,000.00
   First 15 values : [np.float64(1000000.0), np.float64(2000000.0), np.float64(2500000.0), np.float64(3000000.0), np.float64(4000000.0), np.float64(4120000.0), np.float64(5000000.0), np.float64(5500000.0), np.float64(6000000.0), np.float64(6500000.0), np.float64(6900000.0), np.float64(6922000.0), np.float64(7000000.0), np.float64(7500000.0), np.float64(8000000.0)]
   Last 15 values  : [np.float64(60000000.0), np.float64(70000000.0), np.float64(80000000.0), np.float64(100000000.0), np.float64(115000000.0), np.float64(160000000.0), np.float64(200000000.0), np.float64(250000000.0), np.float64(300000000.0), np.float64(400000000.0), np.float64(500000000.0), np.float64(550000000.0), np.float64(600000000.0), np.float64(1023000000.0), np.float64(1599735000.0)]
--------------------------------------------------------------------------------
🔹 Cột: Tiền gốc còn lại  |  Unique: 526
   Min: 0.00  |  Max: 1,598,455,212.00
   First 15 values : [np.float64(0.0), np.float64(658.0), np.float64(16913.0), np.float64(19834.0), np.float64(22000.0), np.float64(180000.0), np.float64(217500.0), np.float64(292000.0), np.float64(294290.0), np.float64(330000.0), np.float64(335130.0), np.float64(360000.0), np.float64(372000.0), np.float64(375000.0), np.float64(397900.0)]
   Last 15 values  : [np.float64(95500000.0), np.float64(100000000.0), np.float64(115000000.0), np.float64(120000000.0), np.float64(123488310.0), np.float64(150000000.0), np.float64(200000000.0), np.float64(220000000.0), np.float64(300000000.0), np.float64(400000000.0), np.float64(500000000.0), np.float64(550000000.0), np.float64(600000000.0), np.float64(1023000000.0), np.float64(1598455212.0)]
--------------------------------------------------------------------------------
🔹 Cột: CardNumber  |  Unique: 1868
   Min: 10,265,696.00  |  Max: 380,147,004,034.00
   First 15 values : [np.int64(10265696), np.int64(11038741), np.int64(11054282), np.int64(11082175), np.int64(11330331), np.int64(11347449), np.int64(11353352), np.int64(11374076), np.int64(11485980), np.int64(11488195), np.int64(11507958), np.int64(11524214), np.int64(11528239), np.int64(11614457), np.int64(11669154)]
   Last 15 values  : [np.int64(79190006295), np.int64(79192000518), np.int64(79192005428), np.int64(79193004883), np.int64(79193005142), np.int64(79194005261), np.int64(80096000055), np.int64(80166000088), np.int64(82185000556), np.int64(89086000062), np.int64(93182000196), np.int64(95197000004), np.int64(133188000003), np.int64(371800015000), np.int64(380147004034)]
--------------------------------------------------------------------------------
🔹 Cột: Salary  |  Unique: 108
   Min: 1,000.00  |  Max: 100,000,000.00
   First 15 values : [np.float64(1000.0), np.float64(10000.0), np.float64(1500000.0), np.float64(2000000.0), np.float64(3000000.0), np.float64(3300000.0), np.float64(3500000.0), np.float64(3700000.0), np.float64(3750000.0), np.float64(3800000.0), np.float64(3975000.0), np.float64(4000000.0), np.float64(4100000.0), np.float64(4200000.0), np.float64(4400000.0)]
   Last 15 values  : [np.float64(21200000.0), np.float64(23000000.0), np.float64(23500000.0), np.float64(24000000.0), np.float64(25000000.0), np.float64(27000000.0), np.float64(30000000.0), np.float64(31000000.0), np.float64(35000000.0), np.float64(40000000.0), np.float64(45000000.0), np.float64(50000000.0), np.float64(60000000.0), np.float64(80000000.0), np.float64(100000000.0)]
--------------------------------------------------------------------------------
🔹 Cột: LongestOverdue  |  Unique: 87
   Min: -23.00  |  Max: 206.00
   First 15 values : [np.int64(-23), np.int64(-18), np.int64(-15), np.int64(-13), np.int64(-10), np.int64(-9), np.int64(-8), np.int64(-5), np.int64(-3), np.int64(-2), np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3)]
   Last 15 values  : [np.int64(79), np.int64(82), np.int64(83), np.int64(84), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(99), np.int64(114), np.int64(120), np.int64(133), np.int64(147), np.int64(175), np.int64(206)]
--------------------------------------------------------------------------------
🔹 Cột: NumberOfLoans  |  Unique: 8
   Min: -1.00  |  Max: 6.00
   All unique values: [np.int64(-1), np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6)]
--------------------------------------------------------------------------------

In [64]:
print("\nNumberOfLoans - Giá trị âm:")
print(df[df['NumberOfLoans'] < 0]['NumberOfLoans'].value_counts())

NumberOfLoans - Giá trị âm:
NumberOfLoans
-1    480
Name: count, dtype: int64

In [65]:
#HANDLE NEGATIVE VALUES IN NUMERICAL COLUMNS

# Check negative values before processing
print("BEFORE PROCESSING:")
print(f"NumberOfLoans has negative values: {(df['NumberOfLoans'] < 0).sum()} records")

# Process only NumberOfLoans: Convert negative values to 0
# (Number of loans cannot be negative)
df['NumberOfLoans'] = df['NumberOfLoans'].clip(lower=0)

print("\n PROCESSING COMPLETED!")
print(f"NumberOfLoans has negative values remaining: {(df['NumberOfLoans'] < 0).sum()}")

#SUMMARY AFTER PROCESSING
print("\n=== SUMMARY AFTER PROCESSING ===")
print(df['NumberOfLoans'].describe().round(2))

BEFORE PROCESSING:
NumberOfLoans has negative values: 480 records

 PROCESSING COMPLETED!
NumberOfLoans has negative values remaining: 0

=== SUMMARY AFTER PROCESSING ===
count    2383.00
mean        1.01
std         1.28
min         0.00
25%         0.00
50%         1.00
75%         2.00
max         6.00
Name: NumberOfLoans, dtype: float64

#Remane columns to English

In [75]:
#RENAME COLUMNS TO ENGLISH

# Define mapping from Vietnamese to English column names
column_mapping = {
    'Số tiền đăng ký vay ban đầu': 'InitialLoanAmount',
    'Tiền giải ngân': 'DisbursedAmount',
    'Tiền gốc còn lại': 'RemainingPrincipal',
    'Số điện thoại khách hàng': 'PhoneNumber',
    'Hình thức cư trú': 'ResidenceType',
    'Thời gian đã sống': 'YearsOfResidence',
    'NameCompany': 'CompanyName',
    'AddressCompany': 'CompanyAddress',
    'CityCompany': 'CompanyCity',
    'DistrictNameCompany': 'CompanyDistrict',
    'RelativeFamilyName': 'RelativeFamilyName',
    'FullNameFamily': 'FamilyFullName',
    'InterestPaymentType': 'InterestPaymentType',
    'Trạng thái': 'Status',
    'CityNameHouseHold': 'HouseholdCity',
    'DistrictNameHouseHold': 'HouseholdDistrict',
    'WardNameHouseHold': 'HouseholdWard'
}

# Apply the new column names
df = df.rename(columns=column_mapping)

print("Successfully renamed all columns to English!")
print("\nNew column names:")
print(df.columns.tolist())

Successfully renamed all columns to English!

New column names:
['application_date', 'TS_CREDIT_SCORE_V2', 'PhoneNumber', 'FromDate', 'ID', 'LoanID', 'InitialLoanAmount', 'DisbursedAmount', 'RemainingPrincipal', 'ToDate', 'Status', 'FullName', 'CardNumber', 'Gender', 'Birthday', 'CityName', 'DistrictName', 'WardName', 'ResidenceType', 'YearsOfResidence', 'Street', 'HouseholdCity', 'HouseholdDistrict', 'HouseholdWard', 'JobName', 'CompanyName', 'CompanyAddress', 'CompanyCity', 'CompanyDistrict', 'Salary', 'ReceiveYourIncomeSalary', 'DescriptionPositionJob', 'RelativeFamilyName', 'FamilyFullName', 'ProductCreditName', 'InterestPaymentType', 'LongestOverdue', 'CreditInfo', 'Name', 'Address', 'CheckTime', 'Brieft', 'NumberOfLoans', 'HasBadDebt', 'HasLatePayment']

In [83]:
#COMPREHENSIVE COLUMN CHECK

print("📋 COMPREHENSIVE DATAFRAME SUMMARY\n")
print(f"Total rows: {df.shape[0]:,}")
print(f"Total columns: {df.shape[1]}\n")

# Create summary table
summary = pd.DataFrame({
    'Column Name': df.columns,
    'Data Type': df.dtypes,
    'Non-Null Count': df.count().values,
    'Missing Count': df.isnull().sum().values,
    'Missing %': (df.isnull().mean() * 100).round(2).values,
    'Unique Values': df.nunique().values
})

# Sort by missing percentage (highest first)
summary = summary.sort_values(by='Missing %', ascending=False).reset_index(drop=True)

# Display the full summary
print(summary.to_string(index=False))

# Additional useful information
print("\n" + "="*80)
print("DATA TYPES SUMMARY:")
print(df.dtypes.value_counts())

print("\n" + "="*80)
print("SAMPLE DATA (first 5 rows):")
display(df.head())

📋 COMPREHENSIVE DATAFRAME SUMMARY

Total rows: 2,383
Total columns: 45

            Column Name      Data Type  Non-Null Count  Missing Count  Missing %  Unique Values
       application_date         object            2383              0        0.0            665
     TS_CREDIT_SCORE_V2          int64            2383              0        0.0            432
            PhoneNumber string[python]            2383              0        0.0           1864
               FromDate datetime64[ns]            2383              0        0.0            665
                     ID string[python]            2383              0        0.0           2383
                 LoanID string[python]            2383              0        0.0           2383
      InitialLoanAmount        float64            2383              0        0.0             55
        DisbursedAmount        float64            2383              0        0.0             57
     RemainingPrincipal        float64            2383              0        0.0            526
                 ToDate datetime64[ns]            2383              0        0.0            840
                 Status       category            2383              0        0.0              4
               FullName string[python]            2383              0        0.0           1752
             CardNumber          int64            2383              0        0.0           1868
                 Gender       category            2383              0        0.0              3
               Birthday         object            2383              0        0.0           1608
               CityName string[python]            2383              0        0.0             13
           DistrictName string[python]            2383              0        0.0             58
               WardName string[python]            2383              0        0.0            226
          ResidenceType       category            2383              0        0.0              7
       YearsOfResidence       category            2383              0        0.0              9
                 Street string[python]            2383              0        0.0           2052
          HouseholdCity string[python]            2383              0        0.0             57
      HouseholdDistrict string[python]            2383              0        0.0            225
          HouseholdWard string[python]            2383              0        0.0            585
                JobName       category            2383              0        0.0             47
            CompanyName string[python]            2383              0        0.0           1750
         CompanyAddress string[python]            2383              0        0.0           1937
            CompanyCity string[python]            2383              0        0.0             12
        CompanyDistrict string[python]            2383              0        0.0            225
                 Salary        float64            2383              0        0.0            108
ReceiveYourIncomeSalary       category            2383              0        0.0              6
 DescriptionPositionJob string[python]            2383              0        0.0           1594
     RelativeFamilyName string[python]            2383              0        0.0              6
         FamilyFullName string[python]            2383              0        0.0           1573
      ProductCreditName       category            2383              0        0.0             10
    InterestPaymentType       category            2383              0        0.0              4
         LongestOverdue          int64            2383              0        0.0             87
             CreditInfo string[python]            2383              0        0.0             33
                   Name string[python]            2383              0        0.0           1598
                Address string[python]            2383              0        0.0           1676
              CheckTime         object            2383              0        0.0           1759
                 Brieft string[python]            2383              0        0.0             16
          NumberOfLoans          int64            2383              0        0.0              7
             HasBadDebt       category            2383              0        0.0              2
         HasLatePayment       category            2383              0        0.0              2

================================================================================
DATA TYPES SUMMARY:
string[python]    22
int64              4
float64            4
object             3
datetime64[ns]     2
category           2
category           1
category           1
category           1
category           1
category           1
category           1
category           1
category           1
Name: count, dtype: int64

================================================================================
SAMPLE DATA (first 5 rows):

,application_date,TS_CREDIT_SCORE_V2,PhoneNumber,FromDate,ID,LoanID,InitialLoanAmount,DisbursedAmount,RemainingPrincipal,ToDate,...,InterestPaymentType,LongestOverdue,CreditInfo,Name,Address,CheckTime,Brieft,NumberOfLoans,HasBadDebt,HasLatePayment
0,Unknown,403,977966899,2016-06-24,40,16104,10000000.0,10000000.0,10000000.0,2016-07-23,...,Lãi ngày,4,Unknown,Unknown,Unknown,2019-03-17 11:22:15,notfound,0,No,No
1,2016-07-28 00:00:00,403,977966899,2016-07-28,226,20871,10000000.0,10000000.0,0.0,2017-03-24,...,Lãi ngày,147,Unknown,Unknown,Unknown,2019-03-17 11:22:15,notfound,0,No,No
2,2016-06-29 00:00:00,531,397511119,2016-06-29,45,17049,5000000.0,5000000.0,5000000.0,2016-12-10,...,Lãi ngày,3,"Khách hàng hiện không có quan hệ tại TCTD, khô...",Dao Cong Quyet,"P203-E9 Phuong Mai,Dong Da,Ha Noi",2019-03-17 08:29:24,0,0,No,No
3,2016-06-29 00:00:00,588,abc1234567,2016-06-29,48,17067,10000000.0,10000000.0,10000000.0,2016-10-26,...,Lãi ngày,16,"Khách hàng hiện không có quan hệ tại TCTD, khô...",Nguyen Anh Vu,So 21 Ngach 77/4 Le Hong Phong-Dien Bien-Ba Di...,2019-03-17 08:28:09,0,0,No,No
4,2016-08-05 00:00:00,675,966710180,2016-08-05,293,22390,10000000.0,10000000.0,0.0,2016-12-02,...,Lãi ngày,8,"Khách hàng hiện không có quan hệ tại TCTD, khô...",Đào Ngọc Linh,"-, Tt Cục Khí Tượng Thủy Văn, Trung Liệt, Q.Đố...",2019-03-17 14:14:22,0,0,No,No

In [84]:
output_processed_csv_file_path = '/content/drive/MyDrive/Tima_CRM_processed.csv'
df.to_csv(output_processed_csv_file_path, index=False)
print(f"Processed DataFrame saved to: {output_processed_csv_file_path}")

Processed DataFrame saved to: /content/drive/MyDrive/Tima_CRM_processed.csv

In [78]:
#CONVERT DATA TYPES

# 1. Convert to Datetime
datetime_cols = ['application_date', 'Birthday', 'CheckTime']

for col in datetime_cols:
    if col in df.columns:
        df[col] = pd.to_datetime(df[col], errors='coerce')
        print(f"✓ Converted '{col}' to datetime")

# 2. Convert to String
string_cols = [
    'FullName',
    'Street',
    'CompanyName',
    'CompanyAddress',
    'DescriptionPositionJob',
    'RelativeFamilyName',
    'FamilyFullName',
    'Name',
    'Address'
]

for col in string_cols:
    if col in df.columns:
        df[col] = df[col].astype('string')
        print(f"Converted '{col}' to string")

# 3. Convert to Category
category_cols = ['JobName']

for col in category_cols:
    if col in df.columns:
        df[col] = df[col].astype('category')
        print(f"✓ Converted '{col}' to category")

#FINAL CHECK
print("DATA TYPE CONVERSION COMPLETED!")

print("\nData types of converted columns:")
converted_cols = datetime_cols + string_cols + category_cols
print(df[converted_cols].dtypes)

✓ Converted 'application_date' to datetime
✓ Converted 'Birthday' to datetime
✓ Converted 'CheckTime' to datetime
Converted 'FullName' to string
Converted 'Street' to string
Converted 'CompanyName' to string
Converted 'CompanyAddress' to string
Converted 'DescriptionPositionJob' to string
Converted 'RelativeFamilyName' to string
Converted 'FamilyFullName' to string
Converted 'Name' to string
Converted 'Address' to string
✓ Converted 'JobName' to category
DATA TYPE CONVERSION COMPLETED!

Data types of converted columns:
application_date          datetime64[ns]
Birthday                  datetime64[ns]
CheckTime                 datetime64[ns]
FullName                  string[python]
Street                    string[python]
CompanyName               string[python]
CompanyAddress            string[python]
DescriptionPositionJob    string[python]
RelativeFamilyName        string[python]
FamilyFullName            string[python]
Name                      string[python]
Address                   string[python]
JobName                         category
dtype: object

In [85]:
# ====================== CLEAN PHONENUMBER & FULLNAME ======================

# Clean PhoneNumber: Only numbers allowed
df['PhoneNumber'] = df['PhoneNumber'].astype(str).str.strip()
df['PhoneNumber'] = df['PhoneNumber'].apply(
    lambda x: x if x.replace(' ', '').replace('+', '').replace('-', '').isdigit() else 'Unknown'
)

# Clean FullName: Only letters allowed
df['FullName'] = df['FullName'].astype(str).str.strip()
df['FullName'] = df['FullName'].apply(
    lambda x: x if not any(char.isdigit() for char in x) else 'Unknown'
)

# ====================== RESULT ======================
print("Cleaning completed!")
print("PhoneNumber unique values:", df['PhoneNumber'].nunique())
print("FullName unique values :", df['FullName'].nunique())

Cleaning completed!
PhoneNumber unique values: 1864
FullName unique values : 1752

In [88]:
output_latest_csv_file_path = '/content/drive/MyDrive/Tima_CRM_cleaned_latest.csv'
df.to_csv(output_latest_csv_file_path, index=False)
print(f"Latest cleaned DataFrame saved to: {output_latest_csv_file_path}")

Latest cleaned DataFrame saved to: /content/drive/MyDrive/Tima_CRM_cleaned_latest.csv